## Setup

In [1]:
import pandas as pd
import scipy as scp
import numpy as np

#### Vamos trabalhar com o Dataset de Diabetes de Índios Pina

Colunas:

* 0. Número de vezes grávidas
* 1. Concentração de glicose a 2h de um teste de tolerância a glicose.
* 2. Pressão sanguínea diastólica (mm Hg).
* 3. Mensuração da espessura da pregas cutâneas Tricipital (mm).
* 4. Nível sérico de Insulina após 2h (mu U/ml).
* 5. Body mass index (peso em kg/(altura em m)^2).
* 6. Função Pedigree Diabetes.
* 7. Idade (anos).
* 8. Variável Classe (0 ou 1).

In [2]:
dataset_names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataset = pd.read_csv('../dados/pima-indians-diabetes.data.txt', 
                      names= dataset_names)

In [3]:
dataset.head()

   preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [4]:
raw_input = dataset.loc[:, dataset.columns != "class"]
raw_input

     preg  plas  pres  skin  test  mass   pedi  age
0       6   148    72    35     0  33.6  0.627   50
1       1    85    66    29     0  26.6  0.351   31
2       8   183    64     0     0  23.3  0.672   32
3       1    89    66    23    94  28.1  0.167   21
4       0   137    40    35   168  43.1  2.288   33
..    ...   ...   ...   ...   ...   ...    ...  ...
763    10   101    76    48   180  32.9  0.171   63
764     2   122    70    27     0  36.8  0.340   27
765     5   121    72    23   112  26.2  0.245   30
766     1   126    60     0     0  30.1  0.349   47
767     1    93    70    31     0  30.4  0.315   23

[768 rows x 8 columns]

In [5]:
output = dataset.loc[:,"class"]
output

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: class, Length: 768, dtype: int64

### MinMax Scaling

In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
rescaled_input = pd.DataFrame(scaler.fit_transform(raw_input), 
                              columns=raw_input.columns)

In [7]:
rescaled_input

,preg,plas,pres,skin,test,mass,pedi,age
0,0.352941,0.743719,0.590164,0.353535,0.000000,0.500745,0.234415,0.483333
1,0.058824,0.427136,0.540984,0.292929,0.000000,0.396423,0.116567,0.166667
2,0.470588,0.919598,0.524590,0.000000,0.000000,0.347243,0.253629,0.183333
3,0.058824,0.447236,0.540984,0.232323,0.111111,0.418778,0.038002,0.000000
4,0.000000,0.688442,0.327869,0.353535,0.198582,0.642325,0.943638,0.200000
...,...,...,...,...,...,...,...,...
763,0.588235,0.507538,0.622951,0.484848,0.212766,0.490313,0.039710,0.700000
764,0.117647,0.613065,0.573770,0.272727,0.000000,0.548435,0.111870,0.100000
765,0.294118,0.608040,0.590164,0.232323,0.132388,0.390462,0.071307,0.150000
766,0.058824,0.633166,0.491803,0.000000,0.000000,0.448584,0.115713,0.433333
767,0.058824,0.467337,0.573770,0.313131,0.000000,0.453055,0.101196,0.033333

In [8]:
rescaled_input.describe()

,preg,plas,pres,skin,test,mass,pedi,age
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,0.226180,0.607510,0.566438,0.207439,0.094326,0.476790,0.168179,0.204015
std,0.198210,0.160666,0.158654,0.161134,0.136222,0.117499,0.141473,0.196004
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.058824,0.497487,0.508197,0.000000,0.000000,0.406855,0.070773,0.050000
50%,0.176471,0.587940,0.590164,0.232323,0.036052,0.476900,0.125747,0.133333
75%,0.352941,0.704774,0.655738,0.323232,0.150414,0.545455,0.234095,0.333333
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

### Estandardização

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
standardized_input = pd.DataFrame(scaler.fit_transform(raw_input), 
                              columns=raw_input.columns).round(3)

In [10]:
standardized_input

      preg   plas   pres   skin   test   mass   pedi    age
0    0.640  0.848  0.150  0.907 -0.693  0.204  0.468  1.426
1   -0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191
2    1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106
3   -0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042
4   -1.142  0.504 -1.505  0.907  0.766  1.410  5.485 -0.020
..     ...    ...    ...    ...    ...    ...    ...    ...
763  1.828 -0.623  0.356  1.723  0.870  0.115 -0.909  2.532
764 -0.548  0.035  0.046  0.405 -0.693  0.610 -0.398 -0.531
765  0.343  0.003  0.150  0.155  0.280 -0.735 -0.685 -0.276
766 -0.845  0.160 -0.471 -1.288 -0.693 -0.240 -0.371  1.171
767 -0.845 -0.873  0.046  0.656 -0.693 -0.202 -0.474 -0.871

[768 rows x 8 columns]

In [11]:
standardized_input.describe()

,preg,plas,pres,skin,test,mass,pedi,age
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,-0.000020,0.000003,-0.000046,0.000081,-0.000055,-0.000013,0.000030,0.000046
std,1.000765,1.000674,1.000727,1.000570,1.000693,1.000620,1.000651,1.000611
min,-1.142000,-3.784000,-3.573000,-1.288000,-0.693000,-4.060000,-1.190000,-1.042000
25%,-0.845000,-0.685000,-0.367000,-1.288000,-0.693000,-0.596000,-0.688750,-0.786000
50%,-0.251000,-0.122000,0.150000,0.155000,-0.428000,0.001000,-0.300500,-0.361000
75%,0.640000,0.605750,0.563000,0.719000,0.412250,0.585000,0.465750,0.660000
max,3.907000,2.444000,2.735000,4.922000,6.653000,4.456000,5.884000,4.064000

### Normalização

In [12]:
from sklearn.preprocessing import Normalizer
scaler = Normalizer()
normalized_input = pd.DataFrame(scaler.fit_transform(raw_input), 
                              columns=raw_input.columns).round(3)

In [13]:
normalized_input

      preg   plas   pres   skin   test   mass   pedi    age
0    0.034  0.828  0.403  0.196  0.000  0.188  0.004  0.280
1    0.008  0.716  0.556  0.244  0.000  0.224  0.003  0.261
2    0.040  0.924  0.323  0.000  0.000  0.118  0.003  0.162
3    0.007  0.588  0.436  0.152  0.622  0.186  0.001  0.139
4    0.000  0.596  0.174  0.152  0.731  0.188  0.010  0.144
..     ...    ...    ...    ...    ...    ...    ...    ...
763  0.042  0.427  0.322  0.203  0.762  0.139  0.001  0.267
764  0.013  0.812  0.466  0.180  0.000  0.245  0.002  0.180
765  0.027  0.651  0.388  0.124  0.603  0.141  0.001  0.161
766  0.007  0.838  0.399  0.000  0.000  0.200  0.002  0.313
767  0.008  0.736  0.554  0.245  0.000  0.241  0.002  0.182

[768 rows x 8 columns]

In [14]:
normalized_input.describe()

,preg,plas,pres,skin,test,mass,pedi,age
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,0.022650,0.682902,0.402806,0.112076,0.318923,0.186874,0.002707,0.195434
std,0.020965,0.161162,0.153434,0.092533,0.338569,0.063407,0.001919,0.080953
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.032000
25%,0.006000,0.587750,0.317750,0.000000,0.000000,0.146000,0.001000,0.140000
50%,0.017000,0.704500,0.430500,0.114500,0.249500,0.186000,0.002000,0.181000
75%,0.033000,0.801500,0.511000,0.181250,0.633000,0.227000,0.004000,0.239250
max,0.117000,0.974000,0.848000,0.420000,0.970000,0.401000,0.013000,0.617000

### Binarização

In [15]:
from sklearn.preprocessing import Binarizer
scaler = Binarizer(threshold=0.0)
binarized_input = pd.DataFrame(scaler.fit_transform(raw_input), 
                              columns=raw_input.columns).round(3)

In [16]:
binarized_input

     preg  plas  pres  skin  test  mass  pedi  age
0     1.0   1.0   1.0   1.0   0.0   1.0   1.0  1.0
1     1.0   1.0   1.0   1.0   0.0   1.0   1.0  1.0
2     1.0   1.0   1.0   0.0   0.0   1.0   1.0  1.0
3     1.0   1.0   1.0   1.0   1.0   1.0   1.0  1.0
4     0.0   1.0   1.0   1.0   1.0   1.0   1.0  1.0
..    ...   ...   ...   ...   ...   ...   ...  ...
763   1.0   1.0   1.0   1.0   1.0   1.0   1.0  1.0
764   1.0   1.0   1.0   1.0   0.0   1.0   1.0  1.0
765   1.0   1.0   1.0   1.0   1.0   1.0   1.0  1.0
766   1.0   1.0   1.0   0.0   0.0   1.0   1.0  1.0
767   1.0   1.0   1.0   1.0   0.0   1.0   1.0  1.0

[768 rows x 8 columns]

In [17]:
normalized_input.describe()

,preg,plas,pres,skin,test,mass,pedi,age
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,0.022650,0.682902,0.402806,0.112076,0.318923,0.186874,0.002707,0.195434
std,0.020965,0.161162,0.153434,0.092533,0.338569,0.063407,0.001919,0.080953
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.032000
25%,0.006000,0.587750,0.317750,0.000000,0.000000,0.146000,0.001000,0.140000
50%,0.017000,0.704500,0.430500,0.114500,0.249500,0.186000,0.002000,0.181000
75%,0.033000,0.801500,0.511000,0.181250,0.633000,0.227000,0.004000,0.239250
max,0.117000,0.974000,0.848000,0.420000,0.970000,0.401000,0.013000,0.617000